2025-02-08 15:30:10,654 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:30:10,658 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:30:11,022 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:30:11,298 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:31:40,343 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:31:40,345 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:31:40,378 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:31:40,657 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:32:21,386 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153010.db
2025-02-08 15:32:21,391 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:32:21,392 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:32:35,459 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_150000.db
2025-02-08 15:32:35,461 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:32:35,462 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:06,401 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153010.db
2025-02-08 15:33:06,405 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:33:06,406 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:12,588 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_142420.db
2025-02-08 15:33:12,595 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:33:12,595 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:58,103 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:33:58,106 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:33:58,453 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:33:58,837 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:34:37,536 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:34:37,544 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:34:37,575 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:34:37,860 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:34:49,962 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153358.db
2025-02-08 15:34:49,968 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:34:49,969 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:35:20,068 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153437.db
2025-02-08 15:35:20,070 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:35:20,071 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:35:25,202 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153358.db
2025-02-08 15:35:25,207 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:35:25,207 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:38:05,471 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:38:05,486 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:38:05,780 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:38:06,074 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:38:30,740 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:38:30,761 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:38:30,797 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:38:31,070 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:38:43,708 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153830.db
2025-02-08 15:38:43,711 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:38:43,712 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 16:00:49,902 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:00:50,272 - app - ERROR - Error al procesar el archivo Excel: 'Campo'
2025-02-08 16:01:31,943 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:01:31,967 - app - ERROR - Error al procesar el archivo Excel: 'Campo'
2025-02-08 16:02:34,855 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:02:34,881 - app - ERROR - Error al procesar el archivo Excel: 'Campo'
2025-02-08 16:03:14,582 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:03:14,654 - app - ERROR - Error al procesar el archivo Excel: 'Campo'
2025-02-08 16:05:27,402 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:05:27,749 - app - ERROR - Error al procesar el archivo Excel: 'Campo'
2025-02-08 16:07:11,777 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:07:11,831 - app - ERROR - Error al procesar el archivo Excel: index 0 is out of bounds for axis 0 with size 0
2025-02-08 16:10:55,888 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:11:27,719 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:11:28,130 - app - ERROR - Error al procesar el archivo Excel: index 0 is out of bounds for axis 0 with size 0
2025-02-08 16:13:22,719 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:13:22,743 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 9A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-08 16:13:22,752 - app - ERROR - Error al procesar el archivo Excel: Worksheet named 'Notas' not found
2025-02-08 16:13:49,365 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:13:49,388 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 9A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-08 16:13:49,406 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 16:13:49,774 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 16:15:08,471 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 16:15:08,824 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 9A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-08 16:15:08,838 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 16:15:09,124 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 16:15:20,915 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-12 15:51:30,760 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_11A.xlsx
2025-02-12 15:51:31,262 - app - ERROR - Error al procesar el archivo Excel: Worksheet named 'Metadatos' not found
2025-02-12 15:51:55,817 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\11_A_-_Excel_Grade_Tracker_Assessment.xlsx
2025-02-12 15:51:55,976 - app - ERROR - Error al procesar el archivo Excel: Worksheet named 'Metadatos' not found
2025-02-12 15:53:05,469 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_11A.xlsx
2025-02-12 15:53:23,804 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_11A.xlsx
2025-02-12 15:53:23,826 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 11A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-12 15:53:23,839 - app - ERROR - Error al procesar el archivo Excel: Worksheet named 'Notas' not found
2025-02-12 15:53:37,972 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_11A.xlsx
2025-02-12 15:53:37,996 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 11A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-12 15:53:38,005 - app - ERROR - Error al procesar el archivo Excel: Worksheet named 'Notas' not found
2025-02-12 15:53:50,048 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_11A.xlsx
2025-02-12 15:53:50,117 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 11A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-12 15:53:50,168 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-12 15:53:50,470 - app - DEBUG - Datos actualizados correctamente.
2025-02-12 15:54:41,637 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-12 15:54:41,662 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 9A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-12 15:54:41,688 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-12 15:54:42,008 - app - DEBUG - Datos actualizados correctamente.
2025-02-12 15:58:14,383 - app - DEBUG - Leyendo la hoja de metadatos del archivo Excel: uploads\notas_9A_.xlsx
2025-02-12 15:58:14,772 - app - DEBUG - Metadatos del archivo: Curso=Ciencias Sociales 9A, Periodo=2025-1, Profesor=Manuel Pimienta
2025-02-12 15:58:14,788 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-12 15:58:15,067 - app - DEBUG - Datos actualizados correctamente.
2025-02-12 15:58:49,979 - app - DEBUG - Procesando filas del archivo Excel...
